spring.application.name=vectoresIA
server.port=8083

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.google.genai.project-id=PracticasIA
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.api-key=AIzaSyCW2KPaspIi6tD1ZhYLIYhj4YkV1odb5Lc
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.vectorstore.pgvector.initialize-schema=true