spring.application.name=vectoresIA
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.google.genai.project-id=PracticasIA
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-flash-latest
spring.ai.vectorstore.pgvector.initialize-schema=true